# -*- coding: utf-8 -*-
"""Python_1°_projeto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy4D3QDl3L8EIW8UcZZZ_yis6dM1GCTS
"""

#Criar lista
lista = [10,20,30,40,50]

#Numero de itens na lista
len(lista)

#Maior iten da lista
max(lista)

#Menor item da lista
min(lista)

#Adicionar item a lista
lista.append(60)

lista

#Adicionar mais de um item de uma vez só
lista.extend([70,80])

#Quantas vezes aparece certo elemento
lista.count(10)

#ordenar a lista
lista.extend([100,90])
lista
lista.sort()
lista

#excluir um elemento
lista.remove(90)
lista.remove(100)
lista



"""# ***Tupla***"""

#Tuplas = listas imutáveis, útil para dicionários, usam parenteses
tupla = (10,20,"trinta","quarenta")

"""# ***Dicionários***"""

#ultilizamos {} para criar
dc = {"Banana":15, "Maçã":10, "Uva":12} #dentro das {} vem o condeito, chave, valor

#Acessar valor através de chave
dc["Banana"]

#Vendo todas as chaves
dc.keys()

#Mudando valor de uma chave
dc["Uva"] = 8
dc

#Todos os valores do dicionário
dc.values()

#Verificar se já existe uma certa 'chave' e 'valor' e se não existir ele irá adicionar
dc.setdefault("Laranja", 20)
dc